name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Build and test with Rake
      run: |
        gem install bundler -v 2.4.22
        gem update --system 3.2.3
        bundle install --jobs 4 --retry 3
        bundle exec rake
